### ISSUE TITLE
Este proyecto palmó, no?

### ISSUE THREAD

**Issue by nicolasdanelon** [linuxitux/sere#3]
che una lastima pero esto va más?

**Comment by linuxitux** [comment]
En realidad lo tengo funcionando en un Devuan 3 y nunca más se me ocurrió agregarle nuevas funcionalidades ni detecté bugs. El problema con este proyecto es que la funcionalidad de reporte provista por SysStat Graph depende de la versión de sysstat instalada (ya que el formato cambia de versión a versión). Esto es un inconveniente aclarado en el proyecto de SysStat Graph y es una limitación que tiene. sere usa una versión de Systat Graph clonada con algunas modificaciones para adaptarse a la versión de sysstat que provee Debian/Devuan.
Si querés hacer modificaciones o seguir el desarrollo te cedo el proyecto.

**Comment by nicolasdanelon** [comment]
Ando sin tiempo y estoy usando plugins de nagios que tirar un dump a una URL publica para monitorear algunas cosas básicas.. encontré en un server viejo una de las primeras versiones de sere y quería saber que onda. Bueno, que andes bien che, saludos

**Comment by linuxitux** [comment]
Si llegás a usarlo y encontrás algún bug avisá. Saludos!!
